### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by lolcabanon** [bryanmylee/meetwhen#24]
Hey! I see there seems to have no license mentioned in this repo, is it on purpose?

Very clean UI btw!

**Comment by bryanmylee** [comment]
Oh this was one of my earliest projects, so I didn't really bother with it. But I can add a simple MIT license if you wanna fork it!

**Comment by lolcabanon** [comment]
I'd love so! 😁

**Comment by lolcabanon** [comment]
:)
